name: 发布版本

on:
    workflow_dispatch:
    push:
        branches:
            - main
env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 
  
jobs:
  build:
    name: 创建
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 设置变量
        id: compile
        run: |
          echo "version=$(bash version.sh)" >> $GITHUB_ENV
          echo "bgcode=$(date +'%Y.%m.%d-%H:%M')" >> $GITHUB_ENV
    
      - name: commit
        run: |
            git config --local user.email "${{ secrets.EMAIL }}"
            git config --local user.name "${{ secrets.NAME }}"
            git pull
            git add version
            git commit -m "update ${{ env.bgcode }}"  
      - name:  Push changes
        uses:  ad-m/github-push-action@master
        with:  
          branch: main
          github_token: ${{ secrets.MY_GIT_TOKEN }}
      - name: 创建发布文本
        run: |  
            echo "版本${{ env.version }}">> release.txt
      - name: 发布到release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body_path: release.txt
          files: ./js/*