name: 发布版本

on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main
env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 
  
jobs:
  build:
    name: 创建
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 设置变量
        id: compile
        run: |
          release_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          branch_name=$(echo ${release_info} | jq -r '.tag_name')
          echo "version_ref=${branch_name}"
          version=$(bash version.sh)
          echo "version=$(bash version.sh)" >> $GITHUB_ENV
          echo "bgcode=$(date +'%Y.%m.%d-%H:%M')" >> $GITHUB_ENV
          if [ "$branch_name" = "$version" ]; then
            result="true"
          else
            result="false"
          fi
          echo "relaese=${result}" >>$GITHUB_ENV
    
      - name: commit
        if: env.relaese == 'true' && !cancelled()
        run: |
            git config --local user.email "${{ secrets.EMAIL }}"
            git config --local user.name "${{ secrets.NAME }}"
            git pull
            git add version
            git commit -m "update ${{ env.bgcode }}"  
      - name:  Push changes
        if: env.relaese == 'true' && !cancelled()
        uses:  ad-m/github-push-action@master
        with:  
          branch: main
          github_token: ${{ secrets.MY_GIT_TOKEN }}
      - name: 创建发布文本
        if: env.relaese == 'true' && !cancelled()
        run: |  
            echo "版本${{ env.version }}">> release.txt
      - name: 发布到release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body_path: release.txt
          files: ./js/*