name: Read Latest Release Branch

on:
  workflow_dispatch

env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 

jobs:
  build:
    name: 创建
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest release info
        id: get_release
        run: |
          release_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          branch_name=$(echo ${release_info} | jq -r '.tag_name')
          echo "version=${branch_name}" >> $GITHUB_ENV

      - name: Use latest release branch name
        run: |
          echo "Using latest release branch ${{ env.version }}"
